php_memcached.lo: /Applications/XAMPP/xamppfiles/htdocs/note-it/memcached-3.1.5/php_memcached.c
	$(LIBTOOL) --mode=compile $(CC) -I/usr/local/Cellar/php@7.4/7.4.20/include/php    -I. -I/Applications/XAMPP/xamppfiles/htdocs/note-it/memcached-3.1.5 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Applications/XAMPP/xamppfiles/htdocs/note-it/memcached-3.1.5/php_memcached.c -o php_memcached.lo 
php_libmemcached_compat.lo: /Applications/XAMPP/xamppfiles/htdocs/note-it/memcached-3.1.5/php_libmemcached_compat.c
	$(LIBTOOL) --mode=compile $(CC) -I/usr/local/Cellar/php@7.4/7.4.20/include/php    -I. -I/Applications/XAMPP/xamppfiles/htdocs/note-it/memcached-3.1.5 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Applications/XAMPP/xamppfiles/htdocs/note-it/memcached-3.1.5/php_libmemcached_compat.c -o php_libmemcached_compat.lo 
g_fmt.lo: /Applications/XAMPP/xamppfiles/htdocs/note-it/memcached-3.1.5/g_fmt.c
	$(LIBTOOL) --mode=compile $(CC) -I/usr/local/Cellar/php@7.4/7.4.20/include/php    -I. -I/Applications/XAMPP/xamppfiles/htdocs/note-it/memcached-3.1.5 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Applications/XAMPP/xamppfiles/htdocs/note-it/memcached-3.1.5/g_fmt.c -o g_fmt.lo 
fastlz/fastlz.lo: /Applications/XAMPP/xamppfiles/htdocs/note-it/memcached-3.1.5/fastlz/fastlz.c
	$(LIBTOOL) --mode=compile $(CC) -I/usr/local/Cellar/php@7.4/7.4.20/include/php    -I. -I/Applications/XAMPP/xamppfiles/htdocs/note-it/memcached-3.1.5 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Applications/XAMPP/xamppfiles/htdocs/note-it/memcached-3.1.5/fastlz/fastlz.c -o fastlz/fastlz.lo 
php_memcached_session.lo: /Applications/XAMPP/xamppfiles/htdocs/note-it/memcached-3.1.5/php_memcached_session.c
	$(LIBTOOL) --mode=compile $(CC) -I/usr/local/Cellar/php@7.4/7.4.20/include/php    -I. -I/Applications/XAMPP/xamppfiles/htdocs/note-it/memcached-3.1.5 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Applications/XAMPP/xamppfiles/htdocs/note-it/memcached-3.1.5/php_memcached_session.c -o php_memcached_session.lo 
$(phplibdir)/memcached.la: ./memcached.la
	$(LIBTOOL) --mode=install cp ./memcached.la $(phplibdir)

./memcached.la: $(shared_objects_memcached) $(MEMCACHED_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_memcached) $(MEMCACHED_SHARED_LIBADD)

